server:
  port: 9296

spring:
  application:
    name: config-Server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/jinkaravi504/microservices-practice-dailycodebuffer-configserver
          #basedir: /Userdisk/Ravi/config-repo-cache
          clone-on-start: true


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch:registry: true
    register-with-eureks: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}