server:
  port: 8082

spring:
  application:
    name: Order_Service

  config:
    import: configserver:http://localhost:9296

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/order-service
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch:registry: true
#    register-with-eureks: true
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}