server:
  port: 8082

spring:
  application:
    name: Order-Service

  config:
    import: optional:configserver:http://localhost:9296

  cloud:
    config:
      enabled: true
      retry:
        max-attempts: 3
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.5

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/order-service
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch:registry: true
#    register-with-eureks: true
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}